import type { Book, PotentialCustomer, Lead } from './types';

// Data parsed and consolidated from the provided OCR documents.
export const BOOKS: Book[] = [
  { id: '10585', title: "Ageing in Asia:Contemporary Trends and Policy Issues", author: "Kai Hong Phua, Lee Gan Goh, Mui Teng Yap", subject: "Social Science", description: "Examines the social and economic implications of aging populations across Asia." },
  { id: '10683', title: "The Geometry, Topology and Physics of Moduli Spaces of Higgs Bundles:", author: "Graeme Wilkin", subject: "Physics", description: "A deep dive into the mathematical structures of Higgs bundles." },
  { id: '10882', title: "New Humanism and Global Governance:", author: "Wei SHAN, Lance L. P. Gore", subject: "Political Science", description: "Discusses new approaches to global governance in a multipolar world." },
  { id: '10976', title: "Critical Issues in Asset Building in Singapore's Development:", author: "Bilveer Singh, S Vasoo", subject: "Economics", description: "Analyzes asset-building policies and their impact on Singapore's development." },
  { id: '11095', title: "Reform and Development in China:After 40 Years", author: "Wei Shan, Yongnian ZHENG, Litao ZHAO, Jiwei QIAN", subject: "Political Science", description: "Reflections on the four decades of economic reform in China." },
  { id: '11243', title: "Educate, Train and Transform:Toolkit on Medical and Health Professions Education", author: "Dujeepa D. Samarasekera, Matthew C. E. Gwee", subject: "Medicine", description: "A practical toolkit for educators in the medical and health professions." },
  { id: '11262', title: "Chinese Society in the Xi Jinping Era:", author: "Dongtao QI, Litao ZHAO", subject: "Sociology", description: "An analysis of contemporary Chinese society under the leadership of Xi Jinping." },
  { id: '11272', title: "Mathematics of Shapes and Applications:", author: "Anqi Qiu", subject: "Mathematics", description: "Explores the application of mathematics in understanding shapes and forms." },
  { id: '11279', title: "China and East Asian Economic Integration:", author: "Sarah Y TONG, Tuan Yuen KONG", subject: "Economics", description: "Studies the economic integration between China and other East Asian nations." },
  { id: '11330-vol2', title: "The Political Economy of the BRICS Countries:Volume 2: BRICS and the Global Economy", author: "Soo Yeon Kim, Giulia Mennillo, Rajesh Kumar", subject: "Economics", description: "Volume 2 of a series on the political and economic dynamics of BRICS countries." },
  { id: '11365', title: "China's Economic Modernisation and Structural Changes:Essays in Honour of John Wong", author: "Sarah Y TONG, Yongnian ZHENG, Sarah CHAN, Jiwei QIAN", subject: "Economics", description: "A collection of essays honoring John Wong, focusing on China's economic transformation." },
  { id: '11385', title: "Sustainable Energy Transition in South Asia:Challenges and Opportunities", author: "Tuan Yuen KONG, Christopher Len, Roshni Kapur", subject: "Energy", description: "Examines the move towards sustainable energy in South Asian countries." },
  { id: '11439', title: "Genealogies of Interacting Particle Systems:", author: "S Narayan", subject: "Physics", description: "A study on the lineage and behavior of interacting particle systems." },
  { id: '11468', title: "Metropolitan Circles Development and the Future of Urbanization:", author: "Rongfeng Sun, Lijun Yang, Wei Shan", subject: "Urban Studies", description: "Analyzes the development of metropolitan circles and the future trends of urbanization." },
  { id: '11565', title: "Chineseness and Modernity in a Changing China:Essays in Honour of Professor Wang Gungwu", author: "Litao ZHAO, Yongnian ZHENG", subject: "History", description: "Essays exploring themes of Chineseness and modernity, in honor of Professor Wang Gungwu." },
  { id: '11600', title: "The Chinese Communist Party in Transformation:The Crisis of Identity and Possibility for Renewal", author: "Lance L P GORE", subject: "Political Science", description: "An analysis of the transformation and challenges facing the Chinese Communist Party." },
  { id: '11602', title: "Julian Schwinger Centennial Conference:Proceedings of the Julian Schwinger Centennial Conference", author: "Berthold-Georg Englert", subject: "Physics", description: "Proceedings from the centennial conference celebrating the work of Julian Schwinger." },
  { id: '11637', title: "Voices on South Asia:Interdisciplinary Perspectives on Women's Status, Challenges and Futures", author: "Silvia Tieri, Vani Swarupa Murali", subject: "Gender Studies", description: "A collection of interdisciplinary views on the status and future of women in South Asia." },
  { id: '11677', title: "Beating the Odds Together:50 Years of Singapore-Israel Ties", author: "Mattia Tomba", subject: "International Relations", description: "Chronicles the 50-year diplomatic relationship between Singapore and Israel." },
  { id: '11876', title: "Maritime Sri Lanka:Historical and Contemporary Perspectives", author: "CHULANEE ATTANAYAKE", subject: "History", description: "A look at the historical and modern maritime significance of Sri Lanka." },
  { id: '11922', title: "Digital Currency Economics and Policy:", author: "Bernard Yeung", subject: "Economics", description: "An exploration of the economics and policy implications of digital currencies." },
  { id: '11944', title: "India on Our Minds:Essays by Tharman Shanmugaratnam and 50 Singaporean Friends of India", author: "Hernaikh Singh", subject: "International Relations", description: "Essays on India-Singapore relations by Tharman Shanmugaratnam and others." },
  { id: '12022', title: "Medical Social Work in Singapore:Context and Practice", author: "Geok Ling LEE", subject: "Social Work", description: "A guide to the context and practice of medical social work in Singapore." },
  { id: '12072', title: "Impact of COVID-19 on Asian Economies and Policy Responses:", author: "Wenlan Qian, Yu Qin, Ben Charoenwong, Bernard Yeung, Sumit Agarwal, Danny Quah", subject: "Economics", description: "Analyzes the impact of the COVID-19 pandemic on Asian economies and their policy responses." },
  { id: '12076', title: "Human Rights and ASEAN:Indonesian and International Perspectives", author: "Ruth Tan, Weina Zhang", subject: "Political Science", description: "Examines human rights issues within ASEAN from Indonesian and international viewpoints." },
  // FIX: Corrected typo from `id::` to `id:`.
  { id: '12110', title: "Functional Materials for Next-Generation Rechargeable Batteries:", author: "Danny Quah", subject: "Engineering", description: "Research on advanced materials for the next generation of rechargeable batteries." },
  { id: '12240', title: "Religion and Identity Politics:Global Trends and Local Realities", author: "Bernard Yeung, Joseph Cherian, KEVIN Y.L. TAN", subject: "Sociology", description: "Explores the intersection of religion, identity, and politics at global and local levels." },
  { id: '12296', title: "Global Supply Chains in a Glocal World:The Impact of Covid-19 and Digitalisation", author: "Li Lu, Mathew Mathews, Melvin Tay, MABEL C. CHOU, PUAY GUAN GOH", subject: "Business", description: "The impact of COVID-19 and digitalization on global supply chains." },
  { id: '12323', title: "The Asian Monetary Policy Forum:Insights for Central Banking", author: "Guiyang Zhu", subject: "Economics", description: "Insights and discussions from the Asian Monetary Policy Forum on central banking." },
  { id: '12344', title: "COVID-19 Pandemic in Singapore:", author: "Luanxi Mao, Xiaobo Li", subject: "Public Health", description: "A study of the COVID-19 pandemic's impact and response in Singapore." },
  { id: '12400', title: "Contemporary Issues in Mediation:Volume 6", author: "MABEL C. CHOU, PUAY GUAN GOH", subject: "Law", description: "Volume 6 of a series discussing contemporary issues in the field of mediation." },
  { id: '12512', title: "Textbook of Occupational Medicine Practice:", author: "Mabel C. Chou, Bernard Yeung, Paul Tambyah, Steven PL Ooi, Dale A Fisher, Joel Lee, David Koh", subject: "Medicine", description: "A comprehensive textbook on the practice of occupational medicine." },
  { id: '12515', title: "Life Cycle Assessment:New Developments and Multi-Disciplinary Applications", author: "Piya KERDLAP, REGINALD B H TAN, Alvin W. L. EE", subject: "Environmental Science", description: "Covers new developments and applications of Life Cycle Assessment." },
  { id: '12574', title: "Molecular Interactions on Two-Dimensional Materials:", author: "Reginald B. H. TAN, Andrew T. S. Wee, Arramel, Konstantin S. Novoselov, D. V. Andreeva", subject: "Materials Science", description: "An in-depth look at molecular interactions on 2D materials." },
  { id: '12641', title: "Buying Time for Climate Action:Exploring Ways around Stumbling Blocks", author: "K. S. Novoselov, M. Chen, S. Lai", subject: "Environmental Science", description: "Explores strategies to overcome obstacles in climate action." },
  { id: '12779', title: "Uncovering the Science of COVID-19:", author: "Andrew T. S. Wee, Arramel, Jonathan Y H Sim, Vincent T K Chow, Alex R. Cook", subject: "Medicine", description: "Delves into the scientific understanding of the COVID-19 virus." },
  { id: '12798', title: "Migrant Workers in Singapore:Lives and Labour in a Transient Migration Regime", author: "Jacinta I-Pei Chen, Jason Chin-Huat Yap, Li Yang Hsu, Vincent T. K. Chow", subject: "Sociology", description: "A study of the lives and labor conditions of migrant workers in Singapore." },
  { id: '12917', title: "Computability Theory and Foundations of Mathematics:Proceedings of the 9th International Conference on C", author: "De Yun Wang", subject: "Mathematics", description: "Proceedings from the 9th International Conference on Computability Theory." },
  { id: '12958', title: "18th Annual Meeting of the Asia Oceania Geosciences Society:Proceedings of the 18th Annual Meeting of the", author: "Kai Sen Tan", subject: "Geoscience", description: "Proceedings from the 18th annual meeting of the Asia Oceania Geosciences Society." },
  { id: '13041', title: "ASEAN and India:The Way Forward", author: "Ryan Zhe Zhang Lew", subject: "International Relations", description: "Discusses the future of the relationship between ASEAN and India." },
  { id: '13065', title: "Looking Beyond the Frontiers of Science:Dedicated to the 80th Birthday of KK Phua", author: "Brenda S. A. Yeoh, Tim Bunnell, Kellynn Wee, Theodora Lam, Jaclyn L. Neo", subject: "Science", description: "A celebratory volume for the 80th birthday of scientist KK Phua." },
  { id: '13092', title: "Commentary on Singapore:Volume 1: Foreign Policy, Governance and Leadership", author: "Mohan J. Dutta", subject: "Political Science", description: "Volume 1 of a commentary series on Singapore's foreign policy and governance." },
  { id: '13109', title: "Singapore Ageing:Issues and Challenges Ahead", author: "Jaclyn L. Neo, Tim Bunnell, Shona Loong, Brenda S. A. Yeoh", subject: "Sociology", description: "Addresses the various issues and challenges related to Singapore's aging population." },
  { id: '13134', title: "Models and Methods for Quantum Condensation and Fluids:", author: "Yue Yang", subject: "Physics", description: "Covers models and methods for studying quantum condensation and fluids." },
  { id: '13136', title: "Modeling and Simulation for Collective Dynamics:", author: "Yue Yang", subject: "Physics", description: "Focuses on the modeling and simulation of collective dynamics in physical systems." },
  { id: '13172', title: "Non-coding RNA Transcripts in Cancer Therapy:Pre-clinical and Clinical Implications", author: "Shie-Yui Liong, Hernaikh Singh, L. C. Kwek, C. H. Oh, CH Oh", subject: "Medicine", description: "Discusses the role and implications of non-coding RNA in cancer therapy." },
  { id: '13176', title: "Immigrant Integration in Contemporary Singapore:Solutioning Amidst Challenges", author: "Bernard T. G. Tan", subject: "Sociology", description: "Examines the challenges and solutions for immigrant integration in Singapore." },
  { id: '13211', title: "Contemporary Issues in Mediation:Volume 7", author: "Andrew Wee, A. H. Chan", subject: "Law", description: "Volume 7 in the series on contemporary issues in mediation." },
  { id: '13226', title: "Fit for Purpose?:The Futures of Universities", author: "C. H. Oh, C. W. Chong, Z. Ong", subject: "Education", description: "A discussion on the future roles and purposes of universities." },
  { id: '13303', title: "Density Functionals for Many-Particle Systems:Mathematical Theory and Physical Applications of Effective Equ", author: "Berge Englert, Gillian Koh, Bilveer Singh, S Vasoo", subject: "Physics", description: "Covers the mathematical theory and physical applications of density functionals." },
  { id: '13385', title: "19th Annual Meeting of the Asia Oceania Geosciences Society:Proceedings of the 19th Annual Meeting of the", author: "Srinivasan Chokkanathan", subject: "Geoscience", description: "Proceedings from the 19th annual meeting of the Asia Oceania Geosciences Society." },
  { id: '13393', title: "Towards Net-Zero Carbon Initiatives:A Life Cycle Assessment Perspective", author: "Weizhu Bao, Gautam Sethi", subject: "Environmental Science", description: "A life cycle assessment perspective on achieving net-zero carbon emissions." },
  { id: '13412', title: "Biden and Beyond:The United States Rethinks South Asia", author: "Lingzhi Wang, Alan Prem Kumar", subject: "Political Science", description: "An analysis of U.S. policy towards South Asia under and beyond the Biden administration." },
  { id: '13479', title: "Aspects of Computation and Automata Theory with Applications:", author: "Huiyan Eng, Gautam Sethi, Mathew Mathews, Melvin Tay", subject: "Computer Science", description: "Explores various aspects of computation and automata theory with practical applications." },
  { id: '13535', title: "Commentary on Singapore:Volume 2: Economy, Environment and Population", author: "Shanthini Selvarajan", subject: "Economics", description: "Volume 2 of a commentary series on Singapore's economy and environment." },
  { id: '13561', title: "Peace with Nature:50 Inspiring Essays on Nature and the Environment", author: "Mathew Mathews, Melvin Tay, Rebecca Grace Tan Tian En, Ah Eng Lai", subject: "Environmental Science", description: "A collection of 50 essays on nature and environmental conservation." },
  { id: '13649', title: "Contemporary Issues in Mediation:Volume 8", author: "Joel Lee, Tristan Tan, Jonathan Y H Sim", subject: "Law", description: "Volume 8 in the series on contemporary issues in mediation." },
  { id: '13664', title: "On the Langlands Program:Endoscopy and Beyond", author: "Berthold-Georg Englert, Jun Hao Hue", subject: "Mathematics", description: "A study of the Langlands Program, focusing on endoscopy and related topics." },
  { id: '13698', title: "Commentary on Singapore:Volume 3: Culture, Identity and Society", author: "Martin-Isbjörn Trappe", subject: "Sociology", description: "Volume 3 of a commentary series on Singapore's culture, identity, and society." },
  { id: '14052', title: "The Non-uniform Riemann Approach to Stochastic Integration:", author: "Berthold-Georg Englert, Jun Hao Hue, Martin-Isbjörn Trappe, Mikołaj M. Paraniak, Zi Chao Huang", subject: "Mathematics", description: "Presents a non-uniform Riemann approach to the theory of stochastic integration." },
  { id: '14053', title: "Contemporary Issues in Mediation:Volume 9", author: "Shie-Yui Liong", subject: "Law", description: "Volume 9 in the series on contemporary issues in mediation." },
  { id: '1804', title: "Solid State Ionics:Materials and ApplicationsProceedings of the 3rd Asian Conference on Solid State Ionics", author: "Reginald B H Tan", subject: "Materials Science", description: "Proceedings from the 3rd Asian Conference on Solid State Ionics." },
  { id: '9472', title: "Singapore and Switzerland:Secrets to Small State Success", author: "Reginald B.H. TAN, C. Raja Mohan, Hernaikh Singh", subject: "Political Science", description: "An analysis of the success strategies of small states like Singapore and Switzerland." },
];

export const INITIAL_ACTIVE_LEAD: Lead = {
  id: 'c07',
  name: 'National University of Singapore',
  type: 'University',
  interests: ['Asian Studies', 'Economics', 'Medicine', 'Public Policy', 'Social Science', 'Physics', 'Computer Science'],
  purchasedBookIds: ['12240', '12296', '12512', '13393', '13412', '13479'],
  priorityScore: 92,
  justification: "Strong alignment with their extensive research in Asian Studies, Economics, and Medicine. Significant gaps identified in our latest publications on global governance and public policy.",
  recommendedBookIds: ['10585', '10882', '11095', '13092'],
  potentialRevenue: 12500,
};

export const POTENTIAL_CUSTOMERS: PotentialCustomer[] = [
  { id: 'c01', name: 'Northwestern University', type: 'University', interests: ['Chemistry', 'History', 'Statistics'], purchasedBookIds: [] },
  { id: 'c02', name: 'QuantumLeap Research', type: 'Research Institute', interests: ['Quantum Physics', 'Artificial Intelligence', 'Computer Science'], purchasedBookIds: ['10683'] },
  { id: 'c03', name: 'BioGen Innovations', type: 'Corporate R&D', interests: ['Biostatistics', 'Chemistry', 'Medicine'], purchasedBookIds: [] },
  { id: 'c04', name: 'MIT', type: 'University', interests: ['Engineering', 'Computer Science', 'Artificial Intelligence'], purchasedBookIds: ['12110', '13479'] },
  { id: 'c05', name: 'City Central Library', type: 'Public Library', interests: ['History', 'General Science'], purchasedBookIds: [] },
  { id: 'c06', name: 'Stanford Medical School', type: 'University', interests: ['Medicine', 'Biostatistics', 'Artificial Intelligence'], purchasedBookIds: ['11243', '12512'] },
  { id: 'c08', name: 'Nanyang Technological University', type: 'University', interests: ['Engineering', 'Materials Science', 'Urban Studies', 'Business'], purchasedBookIds: ['12574', '12296'] },
  { id: 'c09', name: 'Mahidol University', type: 'University', interests: ['Medicine', 'Public Health', 'Social Work', 'Environmental Science'], purchasedBookIds: ['12022', '12779'] },
  { id: 'c10', name: 'Aalborg University', type: 'University', interests: ['Engineering', 'Energy', 'Urban Studies', 'Computer Science'], purchasedBookIds: ['11385'] },
];
